import { useState } from "react"

function EcommerceAnalysis() {

  const [amount, setAmount] = useState("")
  const [quantity, setQuantity] = useState("")
  const [category, setCategory] = useState("")
  const [payment, setPayment] = useState("")

  const [result, setResult] = useState(null)

  const analyzeTransaction = () => {

    if (!amount || !quantity || !category || !payment) {
      setResult({
        type: "error",
        message: "Please enter all transaction details."
      })
      return
    }

    // Temporary frontend result.
    // Later this will call the Model 2 backend API.

    setResult({
      type: "safe",
      message: "Transaction analyzed successfully."
    })
  }

  return (
    <div className="ecommerce-page">

      <div className="page-eyebrow">
        MODEL 2 • E-COMMERCE
      </div>

      <h1>Transaction Analysis</h1>

      <p className="page-description">
        Analyze an online shopping transaction using the NEXRA E-Commerce
        Fraud Detection model.
      </p>

      <div className="analysis-grid">

        {/* INPUT PANEL */}

        <div className="dashboard-card">

          <h2>Transaction Details</h2>

          <p className="card-subtitle">
            Enter e-commerce transaction information
          </p>

          <div className="form-grid">

            <div>
              <label>Transaction Amount</label>

              <input
                type="number"
                placeholder="₹ 50000"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
              />
            </div>

            <div>
              <label>Product Quantity</label>

              <input
                type="number"
                placeholder="1"
                value={quantity}
                onChange={(e) => setQuantity(e.target.value)}
              />
            </div>

            <div>
              <label>Product Category</label>

              <select
                value={category}
                onChange={(e) => setCategory(e.target.value)}
              >
                <option value="">Select category</option>
                <option>Electronics</option>
                <option>Fashion</option>
                <option>Grocery</option>
                <option>Home & Furniture</option>
                <option>Beauty</option>
                <option>Other</option>
              </select>
            </div>

            <div>
              <label>Payment Method</label>

              <select
                value={payment}
                onChange={(e) => setPayment(e.target.value)}
              >
                <option value="">Select payment method</option>
                <option>Credit Card</option>
                <option>Debit Card</option>
                <option>UPI</option>
                <option>Net Banking</option>
                <option>Wallet</option>
              </select>
            </div>

          </div>

          <button
            className="primary-button"
            onClick={analyzeTransaction}
          >
            Analyze Transaction
          </button>

        </div>


        {/* RESULT PANEL */}

        <div className="dashboard-card">

          <h2>Fraud Intelligence</h2>

          <p className="card-subtitle">
            AI prediction generated by Model 2
          </p>

          {!result && (
            <div className="empty-result">
              <div className="result-icon">◇</div>

              <h3>Awaiting Analysis</h3>

              <p>
                Enter transaction details and run the Model 2 analysis.
              </p>
            </div>
          )}

          {result && (
            <div className={`prediction-result ${result.type}`}>

              <div className="result-icon">
                {result.type === "safe" ? "✓" : "!"}
              </div>

              <h3>
                {result.type === "safe"
                  ? "Analysis Complete"
                  : "Input Required"}
              </h3>

              <p>{result.message}</p>

            </div>
          )}

        </div>

      </div>

    </div>
  )
}

export default EcommerceAnalysis