import { useState } from "react"

function Alerts() {
  const [filter, setFilter] = useState("All Alerts")

  const alerts = [
    {
      id: "ALT-5021",
      title: "Unusual Transaction Pattern",
      description: "Multiple high-value transactions detected",
      user: "Aarav Mehta",
      amount: "₹84,500",
      risk: 91,
      level: "Critical",
      status: "Open",
      time: "2 min ago",
    },
    {
      id: "ALT-5020",
      title: "New Device Detected",
      description: "Transaction initiated from an unrecognized device",
      user: "Kabir Singh",
      amount: "₹46,200",
      risk: 72,
      level: "High",
      status: "Investigating",
      time: "8 min ago",
    },
    {
      id: "ALT-5019",
      title: "Multiple Failed Attempts",
      description: "Several authentication failures detected",
      user: "Vihaan Patel",
      amount: "₹1,24,800",
      risk: 96,
      level: "Critical",
      status: "Open",
      time: "16 min ago",
    },
    {
      id: "ALT-5018",
      title: "Location Anomaly",
      description: "Transaction location differs from usual activity",
      user: "Ishita Kapoor",
      amount: "₹28,900",
      risk: 64,
      level: "Medium",
      status: "Review",
      time: "21 min ago",
    },
    {
      id: "ALT-5017",
      title: "Unusual Transaction Amount",
      description: "Transaction exceeds user's normal spending pattern",
      user: "Riya Sharma",
      amount: "₹12,800",
      risk: 58,
      level: "Medium",
      status: "Review",
      time: "29 min ago",
    },
    {
      id: "ALT-5016",
      title: "Trusted Device Activity",
      description: "Transaction matches normal user behaviour",
      user: "Ananya Rao",
      amount: "₹7,450",
      risk: 18,
      level: "Low",
      status: "Resolved",
      time: "34 min ago",
    },
  ]

  const filteredAlerts =
    filter === "All Alerts"
      ? alerts
      : alerts.filter((alert) => alert.level === filter)

  return (
    <div className="page alerts-page">

      {/* PAGE HEADING */}
      <div className="page-heading">
        <div>
          <p className="eyebrow">THREAT INTELLIGENCE</p>

          <h1>Alerts</h1>

          <p className="subtitle">
            Review and investigate suspicious activity
          </p>
        </div>

        {/* FILTER */}
        <div className="alert-filter-wrapper">
          <button
            type="button"
            className="alert-filter-button"
            onClick={() =>
              setFilter(
                filter === "All Alerts"
                  ? "Critical"
                  : filter === "Critical"
                  ? "High"
                  : filter === "High"
                  ? "Medium"
                  : "All Alerts"
              )
            }
          >
            <span>{filter}</span>
            <span className="filter-arrow">⌄</span>
          </button>
        </div>
      </div>


      {/* ALERT SUMMARY */}
      <section className="alert-summary">

        <div className="alert-summary-card">
          <div className="summary-top">
            <span>Active Alerts</span>
            <i></i>
          </div>

          <strong>24</strong>

          <small>+6 from yesterday</small>
        </div>


        <div className="alert-summary-card critical-card">
          <div className="summary-top">
            <span>Critical</span>
            <i></i>
          </div>

          <strong>7</strong>

          <small>Requires immediate action</small>
        </div>


        <div className="alert-summary-card">
          <div className="summary-top">
            <span>Investigating</span>
            <i></i>
          </div>

          <strong>11</strong>

          <small>Currently under review</small>
        </div>


        <div className="alert-summary-card safe-card">
          <div className="summary-top">
            <span>Resolved</span>
            <i></i>
          </div>

          <strong>86</strong>

          <small>Last 24 hours</small>
        </div>

      </section>


      {/* ALERT LIST */}
      <section className="panel alerts-panel">

        <div className="panel-header alerts-panel-header">

          <div>
            <h2>Alert Queue</h2>

            <p>
              Latest security alerts generated by the risk engine
            </p>
          </div>

          <span className="alert-count">
            {filteredAlerts.length} alerts
          </span>

        </div>


        {/* TABLE HEADER */}
        <div className="alerts-table-head">

          <span>Alert</span>
          <span>User</span>
          <span>Amount</span>
          <span>Risk Score</span>
          <span>Level</span>
          <span>Status</span>
          <span>Time</span>

        </div>


        {/* ALERT ROWS */}
        <div className="alerts-list">

          {filteredAlerts.map((alert) => (

            <div
              className="alert-table-row"
              key={alert.id}
            >

              {/* ALERT */}
              <div className="alert-main">

                <div className={`alert-icon ${alert.level.toLowerCase()}`}>
                  !
                </div>

                <div>
                  <strong>{alert.title}</strong>

                  <small>
                    {alert.id} · {alert.description}
                  </small>
                </div>

              </div>


              {/* USER */}
              <span className="alert-user">
                {alert.user}
              </span>


              {/* AMOUNT */}
              <strong className="alert-amount">
                {alert.amount}
              </strong>


              {/* RISK */}
              <div className="alert-risk">

                <div className="alert-risk-bar">
                  <i
                    style={{
                      width: `${alert.risk}%`,
                    }}
                  ></i>
                </div>

                <strong>
                  {alert.risk}
                </strong>

              </div>


              {/* LEVEL */}
              <span
                className={`alert-level ${alert.level.toLowerCase()}`}
              >
                {alert.level}
              </span>


              {/* STATUS */}
              <span
                className={`alert-status ${alert.status
                  .toLowerCase()
                  .replace(" ", "-")}`}
              >
                {alert.status}
              </span>


              {/* TIME */}
              <span className="alert-time">
                {alert.time}
              </span>

            </div>

          ))}

        </div>

      </section>

    </div>
  )
}

export default Alerts